"""Initial migration

Revision ID: 01349fc09f03
Revises: 
Create Date: 2024-10-03 20:02:37.069796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01349fc09f03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_barcode_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_asset_type'), 'asset', ['asset_type'], unique=False)
    op.create_index(op.f('ix_asset_description'), 'asset', ['description'], unique=False)
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_description'), table_name='asset')
    op.drop_index(op.f('ix_asset_asset_type'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
