"""Updated asset model

Revision ID: 437b1f75262c
Revises: 802919aaeb95
Create Date: 2024-11-16 22:03:39.258604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437b1f75262c'
down_revision: Union[str, None] = '802919aaeb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'is_fixed_asset')
    op.add_column('asset', sa.Column('is_fixed_asset', sa.Boolean(), nullable=False))
    op.add_column('asset', sa.Column('hours_state', sa.String(), nullable=True))
    op.add_column('asset', sa.Column('is_working', sa.Boolean(), nullable=True))
    op.alter_column('asset', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_asset_asset_type', table_name='asset')
    op.drop_index('ix_asset_description', table_name='asset')
    op.drop_index('ix_asset_initial_cost', table_name='asset')
    op.drop_index('ix_asset_serial_number', table_name='asset')
    op.drop_column('asset', 'asset_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'is_fixed_asset')
    op.add_column('asset', sa.Column('is_fixed_asset', sa.String(), nullable=False))
    op.add_column('asset', sa.Column('asset_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_asset_serial_number', 'asset', ['serial_number'], unique=False)
    op.create_index('ix_asset_initial_cost', 'asset', ['initial_cost'], unique=False)
    op.create_index('ix_asset_description', 'asset', ['description'], unique=False)
    op.create_index('ix_asset_asset_type', 'asset', ['asset_type'], unique=False)
    op.alter_column('asset', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('asset', 'is_working')
    op.drop_column('asset', 'hours_state')
    # ### end Alembic commands ###
