"""Added Brand Crud, Model, and Schema

Revision ID: 6f79fdb58a8a
Revises: a07dcae450f1
Create Date: 2024-11-16 22:50:20.191875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f79fdb58a8a'
down_revision: Union[str, None] = 'a07dcae450f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'brand', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand', type_='unique')
    # ### end Alembic commands ###
