"""Added serial number to asset

Revision ID: 802919aaeb95
Revises: 91267d301393
Create Date: 2024-10-03 22:31:09.345162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802919aaeb95'
down_revision: Union[str, None] = '91267d301393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('serial_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_asset_serial_number'), 'asset', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_serial_number'), table_name='asset')
    op.drop_column('asset', 'serial_number')
    # ### end Alembic commands ###
