"""Added to asset table

Revision ID: 91267d301393
Revises: 01349fc09f03
Create Date: 2024-10-03 22:22:36.012984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91267d301393'
down_revision: Union[str, None] = '01349fc09f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('is_fixed_asset', sa.String(), nullable=False))
    op.add_column('asset', sa.Column('initial_cost', sa.Float(), nullable=False))
    op.create_index(op.f('ix_asset_initial_cost'), 'asset', ['initial_cost'], unique=False)
    op.create_index(op.f('ix_asset_is_fixed_asset'), 'asset', ['is_fixed_asset'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_is_fixed_asset'), table_name='asset')
    op.drop_index(op.f('ix_asset_initial_cost'), table_name='asset')
    op.drop_column('asset', 'initial_cost')
    op.drop_column('asset', 'is_fixed_asset')
    # ### end Alembic commands ###
