"""Added index and new attributes to Model

Revision ID: 99df1b453e92
Revises: 3971f08a5ce4
Create Date: 2024-11-17 19:53:45.086875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99df1b453e92"
down_revision: Union[str, None] = "3971f08a5ce4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model", sa.Column("id", sa.UUID(), nullable=False))
    op.add_column("model", sa.Column("type", sa.String(), nullable=False))
    op.add_column("model", sa.Column("description", sa.String(), nullable=False))
    op.create_index(op.f("ix_model_id"), "model", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_id"), table_name="model")
    op.drop_column("model", "description")
    op.drop_column("model", "type")
    op.drop_column("model", "id")
    # ### end Alembic commands ###
